#include <uchar.h>
#include <stdint.h>
#include "include/drivers/video_driver.h"
#include "include/io.h"
#include "include/pit.h"
#include "include/drivers/keyboard_driver.h"
#include "include/sys.h"
#include "include/fs.h"
#include "include/cosole.h"
uint8_t size_t_fs = 2;
const uint32_t bitmap[10000] = {
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, White, White, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, LightBlue, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, White, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, LightBlue, LightBlue, LightBlue, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, LightBlue, LightBlue, Black, LightBlue, LightBlue,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, White, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, LightBlue, LightBlue, LightBlue, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Orange, LightBlue, Orange, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Orange, Orange, Orange, Orange, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Orange, Orange, Orange, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Orange, Orange, Orange, Orange, Orange,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Orange, Orange, Orange, Orange, Orange,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Orange, Orange, Orange, Orange, Orange,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Orange, Orange, Orange, Orange, Orange,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Orange, Orange, Orange, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Orange, Orange, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Orange, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Blue, Blue, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Blue, Blue, Blue, Blue, Blue, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Blue, Blue, Blue, Blue, Blue, Blue, Yellow, Yellow, Yellow, Yellow, Green, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Blue, Blue, Blue, Blue, Blue, LightBlue, Blue, Blue, Blue, Yellow, Yellow, Yellow, Green, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Blue, Blue, Blue, Blue, Blue, Blue, LightBlue, LightBlue, Blue, Yellow, Yellow, Yellow, Yellow, Green, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Blue, Blue, Blue, Blue, LightBlue, LightBlue, LightBlue, LightBlue, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Blue, Yellow, LightBlue, LightBlue, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, LightBlue, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Black, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Yellow, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Yellow, Yellow, Yellow, Yellow, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Green, Green, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Green, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Green, Green, Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Green, Green, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
    Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black, Black,
};
const uint32_t fatal_error_ico[900] = {
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0xFFFFFF, 0xFFFFFF, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4,
  0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4, 0x3584E4
};
// kernel.c
void fatal_error(const char* text_error, bool if_exit){
    clear_screen(0x3584E4);
    draw_bitmap32(fatal_error_ico,30,30,20,20);
    print_xy(100,40,"FATAL ERROR",White);
    print_xy(10,300,text_error,White);
    while(1){
        char c = read_char();
        if(c == '\n'||c == '\r'|| c == ' ')
            reboot();
        else if(c == SC_F5)
            if(if_exit)
                return;
    }
}
void itoa(int value, char* str, int base) {
    char* ptr = str, *ptr1 = str, tmp_char;
    int tmp_value;
    if (value == 0) { *str++ = '0'; *str = '\0'; return; }
    while (value != 0) {
        tmp_value = value % base;
        *ptr++ = (tmp_value < 10) ? tmp_value + '0' : tmp_value - 10 + 'A';
        value /= base;
    }
    *ptr-- = '\0';
    while(ptr1 < ptr) {
        tmp_char = *ptr; *ptr = *ptr1; *ptr1 = tmp_char;
        ptr--; ptr1++;
    }
}

void draw_logo(){
    draw_bitmap32(bitmap,100,100,453,300);
    int text_len = sizeof("ParrotOS");           // 9 символов, без '\0'
    int x = 1024 / 2 - (text_len * CHAR_W / 2);
    print_xy(x, 400, "ParrotOS", 0xFFFFFF);
}
bool load_is = false;
int i = 0;
uint16_t buffer_Disk[256];
void init_sys(){
    switch (i/5)
    {
    case 1:
        uint32_t sectors = ide_get_sector_count();
            if (sectors == 0) {
                print_xy(1024 / 2 - (sizeof("No IDE device found") * CHAR_W / 2), 500, "No IDE device found", White);
                fatal_error("No IDE device found", false);
            }
        break;
    case 2:  
        ide_read_sector(1,buffer_Disk);
        break;
    case 3:
        if(buffer_Disk[0]==1){
            //fs_sys=buffer_Disk[1];
            size_t_fs = buffer_Disk[2];
            size_drive = buffer_Disk[3];
        }else
        {
            buffer_Disk[0]=1;
            buffer_Disk[1]=0;
            buffer_Disk[2]=2;
            buffer_Disk[3]=2048;

            ide_write_sector(1,buffer_Disk);
        }
        
        break;
    case 4:
        init_fs(size_t_fs);
    break;
    case 21:
        load_is = true;
    break;
    default:
    
        break;
    }
}
void draw_loading() {
    while (!load_is) {
        // Рисуем рамку прогресс-бара
        draw_cube(108, 21, 1024 / 2 - 54, 447, White);

        // Серый фон
        draw_cube(100, 15, 1024 / 2 - 50, 450, Grey);

        // Зеленая линия
        if(i > 100) i = 0;  // сброс, если дошли до конца
        draw_cube(i, 15, 1024 / 2 - 50, 450, Green);
        i += 5;
        draw_cube(2,15,1024 / 2 - 50+10, 450,Grey);
        draw_cube(2,15,1024 / 2 - 50+20, 450,Grey);
        draw_cube(2,15,1024 / 2 - 50+30, 450,Grey);
        draw_cube(2,15,1024 / 2 - 50+40, 450,Grey);
        draw_cube(2,15,1024 / 2 - 50+50, 450,Grey);
        draw_cube(2,15,1024 / 2 - 50+60, 450,Grey);
        draw_cube(2,15,1024 / 2 - 50+70, 450,Grey);
        draw_cube(2,15,1024 / 2 - 50+80, 450,Grey);
        draw_cube(2,15,1024 / 2 - 50+90, 450,Grey);
        init_sys();
        timer_sleep(100);   // busy-wait или с таймеромread_char();
    }
}

void kernel_main(uint32_t phys_base, uint32_t width, uint32_t height, uint32_t bpp, uint32_t pitch) {
    init_vbe_driver(phys_base, width, height, bpp, pitch);
    clear_screen(Black);
    draw_logo();
    draw_loading();
    main_cmd();
    i=0;
    while (1) {
        char c = read_char();
        print_char_xy(i, 1, c, White);
        i += CHAR_W + CHAR_SPACING;
    }
}
